### ISSUE TITLE
Fix bug in MODE for aspect ratio of nan for objects with an area of 1.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1215]
A met-help question (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=92478) pointed out that for objects with an area of 1, the aspect ratio is being computed as nan.  Randy looked into it and found that objects consisting of a single point yield a length and width of 0 which yield an aspect ratio of 0/0 = nan.

Its not clear exactly how to fix this... whether the length and width *should* be 0 or 1?

**Comment by rgbullock** [comment]
Should be fixed now in the master_v8.1 branch.  In case the length or width of an object is zero then we set relevant attribute values to bad_data_double instead of proceeding with the calculation to ultimately produce a nan.  Note that ShapeData::calc_length_width() uses f_is_on, while the area is calculated with s_is_on.

Single attributes affected:
axis_angle
aspect_ratio
curvature
curvature_x
curvature_y

Pair attributes affected:
angle_diff
aspect_diff
curvature ratio
