### ISSUE TITLE
PCP_combine possible bug, check if fcst_lead is accum_time

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1222]
From methelp ticket 92709

I usually put my forecast data into NETCDF file to make it compatible with MET. I write the NETCDF file according to the output NETCDF file of PCP_combine.

However, I found that output of PCP_combine doesn't set the forecast lead correct. When passing these data to verification tools, such as, grid_stat, the output has wrong FCST_LEAD which is actually the accum_time.

**Comment by JohnHalleyGotway** [comment]
Both Howard Soh and John Halley Gotway looked at this issue but couldn't determine the actual problem. We wrote the user to ask for more information but, not surprisingly, didn't receive a response. The original met-help question was written about 9 months ago, in October 2019. I am closing this issue since we looked into it but didn't find an obvious problem.

If the user does eventually write back with more details, we can consider reopening it.
