### ISSUE TITLE
Slow runtime for regrid_data_plane MAX interpolation in MET-10.0.0_beta5

### ISSUE THREAD

**Issue by LoganDawson-NOAA** [dtcenter/MET#1778]
*Replace italics below with details for this issue.*

## Describe the Problem ##
*When testing the beta5 release for METplus-4.0.0 and MET-10.0.0, I discovered a regrid_data_plane MAX interpolation step that is taking ~8x longer (~12 minutes vs. 90 seconds) to run with MET-10.0.0_beta5 than with MET-9.1. When I initially ran this step in a batch job and from the command line, I thought MET was hanging and unable to complete the interpolation. The input file for this step is a file output by regrid_data_plane at a prior step, so I knew MET shouldn't have a problem reading the file. I ran the command again and realized the interpolation command is simply taking longer to run.*

### Expected Behavior ###
*With MET-9.1, this regrid_data_plane MAX interpolation step took on the order of 90 seconds to complete. With MET-10.0.0_beta5, the same step took upwards of 12 minutes to complete.*

### Environment ###
Describe your runtime environment:
*1. Machine: WCOSS Dell*
*2. OS: Linux*
*3. MET-10.0.0_beta5*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Interpolate the GRIB2 data to G227 using the following command: 
met/10.0.0-beta5/bin/regrid_data_plane -v 5 -method BUDGET -width 2 -field 'name="MergedReflectivityQCComposite"; level="Z500";' -name MergedReflectivityQCComposite MergedReflectivityQCComposite_00.50_20210504-190000.grib2 G227.nc MergedReflectivityQCComposite_00.50_20210504-190000_g227.nc*

*2. Run MAX interpolate on the prior step's output using the following command: 
met/10.0.0-beta5/bin/regrid_data_plane -v 5 -method MAX -width 17 -field 'name="MergedReflectivityQCComposite"; level="Z500";' -name MergedReflectivityQCComposite MergedReflectivityQCComposite_00.50_20210504-190000_g227.nc G227.nc MergedReflectivityQCComposite_MAX40_20210504-190000_g227.nc*

*3. See the significantly slower runtime for the second command. Running the command(s) within a script that can provide timing info would be useful.* 

*4. Running the same two commands with a MET-9.1 executable will show that the runtime is approximately the same for the first interpolation step, but the second step is considerably slower.*

*Both the input file (for step 1 and step 2) and the "to grid" file have been posted to the ftp.rap.ucar.edu site.*

*These commands were generated by METplus-4.0.0_beta5 and METplus-3.1 in my test environment. I can provide the METplus conf files and commands if those would be helpful, but the issue appears isolated to MET itself. I have however attached METplus log files, which provide the output I've seen and the timing information as well.*

[master_metplus.METplus-3.1.log.20210505164635.txt](https://github.com/dtcenter/MET/files/6428916/master_metplus.METplus-3.1.log.20210505164635.txt)
[master_metplus.METplus-4.0.0-beta5.log.20210504230632.txt](https://github.com/dtcenter/MET/files/6428917/master_metplus.METplus-4.0.0-beta5.log.20210504230632.txt)

### Relevant Deadlines ###
*Investigating before MET-10.0.0 official release would be helpful.*

### Funding Source ###
*NONE*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Pulled the sample data to my local machine and am testing there. Checked run times by varying the MAX regridding widths:
- width = 3 has runtimes of 0m28.264s and 0m30.619s for main_v9.1/develop.
- width = 9 has runtimes of 3m6.029s and 3m4.778s for main_v9.1/develop.
- width = 17 has runtimes of 12m7.563s and 11m51.669s for main_v9.1/develop.

Running the same tests on WCOSS/Venus.
```
cd /gpfs/dell2/emc/verification/noscrub/John.H.Gotway/MET/MET_Help/dawson_data_20210505
module use /gpfs/dell2/emc/verification/noscrub/emc.metplus/modulefiles
module load met/9.1.2
./run_pdp.sh
```
- width = 3 has runtimes of 0m32.130s and 0m31.453s for 9.1.2/10.0.0-beta5.
- width = 9 has runtimes of 3m17.513s and 3m18.486s for 9.1.2/10.0.0-beta5.
- width = 17 has runtimes of 12m23.442s and 12m25.119s for 9.1.2/10.0.0-beta5 (still running)

@LoganDawson-NOAA I'm not saying these are desirable runtimes, but I'm just not able to replicate the discrepancy between versions that you describe. I could proceed with profiling the code to see if/how runtimes could be improved in general, but I'm not convinced that this is a new problem introduced by development for MET version 10.0.0.

Is there any other way you'd recommend I test this out?

Note that this is a very special case of calling regrid_data_plane. You're using it to SMOOTH the data rather than actually regrid it. I'd recommend we consider the following enhancements in a future version:

- Complete development for MET #1759 to make the convolution (i.e. smoothing) step in MODE as fast as we can.
- Make sure these data smoothing operations are defined in a common place in the library code.
- Enhance regrid_data_plane to check for input grid = output grid. In that case, call the much faster library smoothing functions instead of the slower regridding functions.
- Profile the code to see how often the code is range change the x, y values passed to DataPlane::get(x,y). Doing that millions of time slows things down! Change the code to minimize those calls.
- Consider using mpi and/or openmp to spread processing across multiple processors.

**Comment by LoganDawson-NOAA** [comment]
@JohnHalleyGotway you're correct that this isn't a new problem introduced in MET-10.0.0. It is however a behavior that's come in after the initial release of MET-9.1, which is the version I've been using since last fall.

I grabbed your run_pdp.sh script and ran a slightly modified version to test MET-9.1, MET-9.1.1, MET-9.1.2, and MET-10.0.0_beta5 (all with width = 17).

- MET-9.1: 1m15.684s
- MET-9.1.1: 12m21.113s
- MET-9.1.2: 12m20.935s
- MET-10.0.0_beta5: 12m26.169s

I didn't test smaller widths last night, but I think you should see the faster runtime with the met/9.1 executable. Maybe the source of the performance change will be easier to track down between the MET-9.1 and MET-9.1.1 code?

And my apologies for not having spotted this sooner with the previous bugfix releases. With my routine verification, it's typically easier to stick with the major releases unless there's a specific new capability I need in a bugfix release. I'm now recognizing the necessity and value in at least fully testing my entire suite of use cases, even with bugfix releases, to make sure prior performance and capabilities are unchanged.

Your idea on moving this smoothing process to a faster capability makes a lot of sense, and I'd definitely be happy to test it with data from my use case.

**Comment by JohnHalleyGotway** [comment]
@LoganDawson-NOAA this is great feedback. Thanks for narrowing it down! I'll debug the difference in runtimes between 9.1 and 9.1.1.
...
Testing the runtime of 9.1 vs 9.1.1 locally on my laptop reveals no apparent discrepancy:
For MET-9.1 and 9.1.1, I got runtimes of **11m9.961s** and **11m55.222s**.
...
But testing on WCOSS, I do see a **major discrepancy** between the two.
For MET-9.1 and 9.1.1, I got runtimes of **1m16.568s** and **12m24.640s**.
...
I did also check to make sure that 9.1 and 9.1.1 produce the same result by running pcp_combine.
```
pcp_combine -subtract rdp_9.1.nc rdp_9.1.1.nc rdp_9.1_minus_9.1.1.nc -field 'name="MergedReflectivityQCComposite"; level="(*,*)";'
```
The differences in the output are all 0 or bad data values.
...
There was no obvious code change for 9.1.1 to explain this:
Release Notes: https://met.readthedocs.io/en/v9.1.3/Users_Guide/overview.html#version-9-1-1-release-notes-20201118
Closed Issues: https://github.com/dtcenter/MET/milestone/68?closed=1
Perhaps the change is due to how 9.1 and 9.1.1 were configured/compiled on WCOSS?

**Comment by JohnHalleyGotway** [comment]
### Compare compilation options:
I compared the compilation flags in config.log for the build configurations of 9.1 and 9.1.1 on WCOSS:
```
egrep "CFLAGS=|CXXFLAGS=|FFLAGS=" /gpfs/dell2/emc/verification/noscrub/emc.metplus/met/9.1/met-9.1/config.log
```
CFLAGS='-D__64BIT__'
CXXFLAGS='-D__64BIT__'
FFLAGS='-g'
```
egrep "CFLAGS=|CXXFLAGS=|FFLAGS=" /gpfs/dell2/emc/verification/noscrub/emc.metplus/met/9.1.1/met-9.1.1/config.log
```
CFLAGS='-g -O2'
CXXFLAGS='-g'
FFLAGS='-g'

I doubt the -D__64BIT__ flag is the the culprit here, but compiling with -g may very likely impact runtime!

### Test removing -g:

I compiled met-9.1 on my laptop without -g, but the runtime was still 12m1.905s. This is compiled with GNU.

Next, I compiled MET's develop branch on WCOSS with/without -g in:
/gpfs/dell2/emc/verification/noscrub/John.H.Gotway/MET/MET_development/MET-no-dash-g/met/bin/regrid_data_plane

The run completes in a (relatively) blazing **1m16.978s** without -g vs **12m26.862s** with -g.

So the culprit here is compiling with the -g option.

@jprestop should we remove '-g' from the default compilation settings in configure.ac?
https://github.com/dtcenter/MET/blob/e45c8dd8ac4dde7404e2c090f7ef0d49e415af55/met/configure.ac#L1048

Any idea about this comment?
```
# The CXXFLAGS default to "-O2 -g".  The optimization is causing
# problems so just set it to "-g" if the user hasn't overridden it
# themselves.
```

**Comment by LoganDawson-NOAA** [comment]
@JohnHalleyGotway thanks for tracking down the runtime difference as a difference in the compilation settings used for the older and newer versions. If it's possible to compile 10.0.0 without the -g option, that'd be great, but I totally understand if that option is necessary to allow some other capability to work correctly.

**Comment by JohnHalleyGotway** [comment]
I am changing the handling of CFLAGS, FFLAGS, and CXXFLAGS in configure.ac.
Prior to this change, running ./configure revealed their default settings:
```
egrep "CFLAGS=|FFLAGS=|CXXFLAGS=" config.log
CFLAGS='-g -O2'
CXXFLAGS='-g'
FFLAGS='-g -O2'
```
Next, I updated configure.ac.
```
# For GNU compilers, CFLAGS, CXXFLAGS, and FFLAGS default to "-O2 -g".
# The CXXFLAGS "-O2" optimization has caused problems in the past.
# For Intel compilers, "-g" slows down runtimes considerably (MET #1778).
# For development, retain the "-g" option. Otherwise, discard it.

AM_COND_IF([ENABLE_DEVELOPMENT], [: ${CFLAGS="-g -O2"}], [: ${CFLAGS="-O2"}])
AM_COND_IF([ENABLE_DEVELOPMENT], [: ${CXXFLAGS="-g"}  ], [: ${CXXFLAGS=""}] )
AM_COND_IF([ENABLE_DEVELOPMENT], [: ${FFLAGS="-g -O2"}], [: ${FFLAGS="-O2"}])
```
 And reran bootstrap and configure with MET_DEVELOPMENT not set:
```
unset MET_DEVELOPMENT; ./bootstrap; ./configure --prefix=`pwd`
egrep "CFLAGS=|FFLAGS=|CXXFLAGS=" config.log
CFLAGS='-O2'
CXXFLAGS=''
FFLAGS='-O2'
```
With MET_DEVELOPMENT set:
```
export MET_DEVELOPMENT=true; ./bootstrap; ./configure --prefix=`pwd`
egrep "CFLAGS=|FFLAGS=|CXXFLAGS=" config.log
CFLAGS='-g -O2'
CXXFLAGS='-g'
FFLAGS='-g -O2'
```
And testing the environment variable overrides:
```
export CFLAGS='-my_cflags'; export CXXFLAGS='-mycxxflags'; export FFLAGS='-my_fflags'
./boostrap; ./configure --prefix=`pwd`
egrep "CFLAGS=|FFLAGS=|CXXFLAGS=" config.log
CFLAGS='-my_cflags'
CXXFLAGS='-mycxxflags'
FFLAGS='-my_fflags'
```
So this is all working as expected.
