### ISSUE TITLE
Bugfix: Intel oneAPI compilers fails to build MET 11.1.0

### ISSUE THREAD

**Issue by HathewayWill** [dtcenter/MET#2778]
## Describe the Problem ##
With the new intel llvm compilers released for 2024.  MET 11.1.0 fails to build MET after compiling all the libraries correctly.

Seems to be a flag issue.

### Expected Behavior ###
should be able to change intel classic compilers (ifort/icc/icpc) for intel llvm compilers (ifx/icx/icpx)

### Environment ###
Describe your runtime environment:
*1. Linux Desktop
*2. OS: Ubuntu 20.04.3
*3. Software version number(s): MET 11.1.0

### To Reproduce ###
Describe the steps to reproduce the behavior:
See files in zip folder for instlal script and log files.
[DTC_LLVM_ERROR.zip](https://github.com/dtcenter/MET/files/13805901/DTC_LLVM_ERROR.zip)

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as the next bugfix version
- [ ] Select **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Select **MET-X.Y.Z Development** project for development toward the next official release

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Close this issue.

**Comment by jprestop** [comment]
Hi @HathewayWill.  The issue created for this work to "[Enhance "compile_MET_all.sh" to support the new Intel oneAPI compilers and upgrade dependent library versions as needed](https://github.com/dtcenter/MET/issues/2611)" was assigned to the beta2 version of the MET-12.0.0 release, so it is not expected that MET-11.1.0 would compile with the new oneAPI (LLVM-based) compilers.   

I believe you should be able to compile MET-11.1.0 with the new oneAPI compilers using the [compile_MET_all.sh script from the develop branch](https://raw.githubusercontent.com/dtcenter/MET/develop/internal/scripts/installation/compile_MET_all.sh) and using the new set of packages ([tar_files.met-base-v3.1.tgz](https://dtcenter.ucar.edu/dfiles/code/METplus/MET/installation/tar_files.met-base-v3.1.tgz)) that we are using as dependencies for the MET-12.0.0 release.  However, there are some changes to the compilation script so you'll want to add the following to your configuration setup, if you don't specify it already:
export FC=ifx
export F77=ifx
export F90=ifx
export CC=icx
export CXX=icpx
Also, the PROJ library will be required for MET-12.0.0, so you'll notice that (along with sqlite and tiff as dependencies of PROJ) being installed unless you would like to point to a location of an existing PROJ directory using the environment variable MET_PROJ.  There are two optional libraries, ATLAS and ECKIT, but you would need to specify that you want those compiled, so you shouldn't need to do anything with those, because we don't want those compiled for MET-11.1.0.  

Please let us know if you have any questions.

**Comment by HathewayWill** [comment]
Thanks you @jprestop 

I'll wait for 12 to be released and test it again.  Go ahead and close this issue.

**Comment by jprestop** [comment]
Closing based on [this comment](https://github.com/dtcenter/MET/issues/2778#issuecomment-1881841563) by @HathewayWill.
